# Generated by Django 6.0.6 on 2026-07-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('full_name', models.CharField(max_length=255, verbose_name='ຊື່ ແລະ ນາມສະກຸນ(真实姓名)')),
                ('name_Chinese', models.CharField(blank=True, max_length=255, unique=True, verbose_name='ຊື່ ແລະ ນາມສະກຸນພາສາຈີນ(真实姓名)')),
                ('organization', models.CharField(max_length=255, verbose_name='ມາຈາກພາກສ່ວນ/ໂຮງຮຽນໃດ')),
                ('district', models.CharField(max_length=100, verbose_name='ເມືອງ (城市)')),
                ('province1', models.CharField(choices=[('ນະຄອນຫຼວງວຽງຈັນ', 'ນະຄອນຫຼວງວຽງຈັນ'), ('ຜົ້ງສາລີ', 'ຜົ້ງສາລີ'), ('ຫຼວງນ້ຳທາ', 'ຫຼວງນ້ຳທา'), ('ອຸດົມໄຊ', 'ອຸດົມໄຊ'), ('ບໍ່ແກ້ວ', 'ບໍ່ແກ້ວ'), ('ຫຼວງພະບາງ', 'ຫຼວງພະບາງ'), ('ຫົວພັນ', 'ຫົວພັນ'), ('ໄຊຍະບູລີ', 'ໄຊຍະບູລີ'), ('ຊຽງຂວາງ', 'ຊຽງຂວາງ'), ('ວຽງຈັນ', 'ວຽງຈັນ'), ('ບໍລິຄຳໄຊ', 'ບໍລິຄຳໄຊ'), ('ຄຳມ່ວນ', 'ຄຳມ່ວນ'), ('ສະຫວັນນະເຂດ', 'ສະຫວັນນະເຂດ'), ('ສາລະວັນ', 'ສາລະວັນ'), ('ເຊກອງ', 'ເຊກອງ'), ('ຈຳປາສັກ', 'ຈຳປາສັກ'), ('ອັດຕະປື', 'ອັດຕະປື'), ('ໄຊສົມບູນ', 'ໄຊສົມບູນ')], default='ນະຄອນຫຼວງວຽງຈັນ', max_length=60, verbose_name='ແຂວງ (省)')),
                ('is_graduated_m7', models.CharField(choices=[('ມໍ7', 'ຈົບແລ້ວ (已毕业)'), ('ຍັງບໍ່ຈົບ', 'ຍັງບໍ່ຈົບ (未毕业)')], max_length=20, verbose_name='ຈົບມໍ 7 ຫຼື ບໍ່? (你七年级毕业嘛)')),
                ('current_grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='ຖ້າບໍ່ຈົບ, ປັດຈຸບັນຮຽນຢູ່ຊັ້ນໃດ?')),
                ('choices_subject', models.CharField(blank=True, choices=[('HSK1', 'HSK1'), ('HSK2', 'HSK2'), ('HSK3', 'HSK3'), ('HSK4', 'HSK4'), ('HSK5', 'HSK5'), ('HSK6', 'HSK6')], max_length=60, verbose_name='ວິຊາເລືອກຮຽນ (选修课程)')),
                ('chinese_level', models.CharField(blank=True, choices=[('HSK1', 'HSK1'), ('HSK2', 'HSK2'), ('HSK3', 'HSK3'), ('HSK4', 'HSK4'), ('HSK5', 'HSK5'), ('HSK6', 'HSK6')], max_length=60, verbose_name='ລະດັບພາສາຈີນ (中文)')),
                ('phone_number', models.CharField(max_length=50, verbose_name='ເບີຕິດຕໍ່ (联络手机)')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='facebook (脸书)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='ຮູບພາບແນບມາ')),
            ],
            options={
                'verbose_name': 'ຂໍ້ມູນການລົງທະບຽນ',
                'verbose_name_plural': 'ຂໍ້ມູນການລົງທະບຽນສອບເສັງພາສາຈີນ',
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_image_field', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='subject_photos/')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('price', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('promotion_end_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(blank=True, max_length=60)),
                ('gender_eng', models.CharField(choices=[('Mr', 'Mr'), ('Miss', 'Miss')], max_length=10)),
                ('gender', models.CharField(choices=[('ນາງ', 'ນາງ'), ('ທ້າວ', 'ທ້າວ'), ('ພຣະ', 'ພຣະ')], max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('Username_lao', models.CharField(max_length=60)),
                ('name_eng', models.CharField(max_length=60)),
                ('Username_eng', models.CharField(max_length=60)),
                ('age', models.CharField(max_length=10)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('Profile', models.TextField(blank=True, default='', null=True)),
                ('Nationality', models.CharField(blank=True, max_length=60)),
                ('Religion', models.CharField(blank=True, max_length=60)),
                ('Buddhism', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('tel', models.CharField(max_length=20)),
                ('province', models.CharField(choices=[('ນະຄອນຫຼວງວຽງຈັນ', 'ນະຄອນຫຼວງວຽງຈັນ'), ('ຜົ້ງສາລີ', 'ຜົ້ງສາລີ'), ('ຫຼວງນ້ຳທາ', 'ຫຼວງນ້ຳທา'), ('ອຸດົມໄຊ', 'ອຸດົມໄຊ'), ('ບໍ່ແກ້ວ', 'ບໍ່ແກ້ວ'), ('ຫຼວງພະບາງ', 'ຫຼວງພະບາງ'), ('ຫົວພັນ', 'ຫົວພັນ'), ('ໄຊຍະບູລີ', 'ໄຊຍະບູລີ'), ('ຊຽງຂວາງ', 'ຊຽງຂວາງ'), ('ວຽງຈັນ', 'ວຽງຈັນ'), ('ບໍລິຄຳໄຊ', 'ບໍລິຄຳໄຊ'), ('ຄຳມ່ວນ', 'ຄຳມ່ວນ'), ('ສະຫວັນນະເຂດ', 'ສະຫວັນນະເຂດ'), ('ສາລະວັນ', 'ສາລະວັນ'), ('ເຊກອງ', 'ເຊກອງ'), ('ຈຳປາສັກ', 'ຈຳປາສັກ'), ('ອັດຕະປື', 'ອັດຕະປື'), ('ໄຊສົມບູນ', 'ໄຊສົມບູນ')], max_length=60)),
                ('districts', models.CharField(max_length=60)),
                ('village', models.CharField(max_length=60)),
                ('Current_province', models.CharField(blank=True, max_length=60)),
                ('Current_districts', models.CharField(blank=True, max_length=60)),
                ('Current_village', models.CharField(blank=True, max_length=60)),
                ('Mobile_Parents', models.CharField(blank=True, max_length=60)),
                ('from_school', models.CharField(max_length=60)),
                ('academic_year', models.CharField(max_length=60)),
                ('semester', models.CharField(max_length=60)),
                ('employee', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=60)),
                ('province_school', models.CharField(blank=True, max_length=60)),
                ('districts_school', models.CharField(blank=True, max_length=60)),
                ('village_school', models.CharField(blank=True, max_length=60)),
                ('Other_Skill', models.CharField(blank=True, max_length=60)),
                ('Skill', models.CharField(blank=True, max_length=60)),
                ('Language', models.CharField(blank=True, max_length=60)),
                ('Language1', models.CharField(blank=True, max_length=60)),
                ('Language2', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('unapproved', 'Unapproved'), ('approved', 'Approved')], default='unapproved', max_length=15)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('subject_set', models.ManyToManyField(to='myapp.subject')),
            ],
        ),
    ]
