# Generated by Django 6.0.6 on 2026-07-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='subject_set',
            field=models.ManyToManyField(to='myapp.subject'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='choices_subject',
            field=models.CharField(blank=True, choices=[('ຄະນິດສາດ', 'ຄະນິດສາດ'), ('ຟິຊິກສາດ', 'ຟິຊິກສາດ'), ('ເຄມີສາດ', 'ເຄມີສາດ'), ('ພາສາອັງກິດ', 'ພາສາອັງກິດ'), ('ພາສາຈີນ', 'ພາສາຈີນ')], max_length=60, verbose_name='ວິຊາເລືອກຮຽນ (选修课程)'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='organization',
            field=models.CharField(max_length=255, verbose_name='ມາຈາກໂຮງຮຽນໃດ(来自哪所学校？)'),
        ),
    ]
