# Generated by Django 6.0.6 on 2026-07-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_formresponse_subject_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formresponse',
            name='choices_subject',
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='subject_set',
            field=models.ManyToManyField(to='myapp.subject', verbose_name='ວິຊາເລືອກຮຽນ (选修课程)'),
        ),
    ]
