# Generated by Django 6.0.6 on 2026-07-22 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_formresponse_choices_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='is_graduated_m7',
            field=models.CharField(choices=[('ມໍ7', 'ຈົບມໍ7ແລ້ວ (已毕业)'), ('ຍັງບໍ່ຈົບ', 'ຍັງບໍ່ຈົບ (未毕业)')], max_length=20, verbose_name='ຫຼັງຈາກເດືອນ9 ສົກ2026 ນີ້ນ້ອງຮຽນຊັ້ນໃດ? (你七年级毕业嘛)'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
    ]
