# Generated by Django 6.0.6 on 2026-07-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_formresponse_is_graduated_m7_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formresponse',
            options={'verbose_name': 'ຂໍ້ມູນການລົງທະບຽນນັກຮຽນທືນວິຕ້າ', 'verbose_name_plural': 'ຂໍ້ມູນການລົງທະບຽນນັກຮຽນທືນວິຕ້າ'},
        ),
        migrations.AddField(
            model_name='formresponse',
            name='Village',
            field=models.CharField(blank=True, max_length=100, verbose_name='ບ້ານ (村莊)'),
        ),
    ]
