# Generated by Django 6.0.6 on 2026-07-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_formresponse_options_formresponse_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='province1',
            field=models.CharField(choices=[('Vientiane Capital', 'ນະຄອນຫຼວງວຽງຈັນ'), ('Phongsaly', 'ຜົ້ງສາລີ'), ('Luang Namtha', 'ຫຼວງນ້ຳທາ'), ('Oudomxay', 'ອຸດົມໄຊ'), ('Bokeo', 'ບໍ່ແກ້ວ'), ('Luang Prabang', 'ຫຼວງພະບາງ'), ('Huaphan', 'ຫົວພັນ'), ('Xayaboury', 'ໄຊຍະບູລີ'), ('Xieng Khouang', 'ຊຽງຂວາງ'), ('Vientiane Province', 'ວຽງຈັນ'), ('Bolikhamxay', 'ບໍລິຄຳໄຊ'), ('Khammouane', 'ຄຳມ່ວນ'), ('Savannakhet', 'ສະຫວັນນະເຂດ'), ('Salavan', 'ສາລະວັນ'), ('Sekong', 'ເຊກອງ'), ('Champasak', 'ຈຳປາສັກ'), ('Attapeu', 'ອັດຕະປື'), ('Xaysomboun', 'ໄຊສົມບູນ')], default='ນະຄອນຫຼວງວຽງຈັນ', max_length=60, verbose_name='ແຂວງເກີດ (省)'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='subject_set',
            field=models.ManyToManyField(to='myapp.subject', verbose_name='ວິຊາເລືອກຮຽນທີ່ສູນປາລີ (选修课程)'),
        ),
    ]
