# Generated by Django 6.0.6 on 2026-07-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_formresponse_province1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Name_eng',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
