# Generated by Django 6.0.6 on 2026-07-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_subject_name_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Name_eng',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
