# Generated by Django 6.0.6 on 2026-07-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_formresponse_province1'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='ວັນເດືອນປີເກີດ (出生日期)'),
        ),
    ]
