# Generated by Django 6.0.6 on 2026-07-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_formresponse_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='ethnicity',
            field=models.CharField(choices=[('Lao', 'ລາວ'), ('Hmong', 'ມົ້ງ'), ('Khmu', 'ກຶມມຸ'), ('Phouthai', 'ຜູ້ໄທ'), ('Tai', 'ໄຕ'), ('Other', 'ອື່ນໆ (Other)')], default='Lao', max_length=50, verbose_name='ຊົນເຜົ່າ (民族)'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='religion',
            field=models.CharField(choices=[('Buddhism', 'ພຸດ'), ('Christianity', 'ຄຣິດ'), ('Islam', 'ອິດສະລາມ'), ('Animism', 'ນັບຖືຜີ / ບໍ່ມີສາດສະໜາ'), ('Other', 'ອື່ນໆ (Other)')], default='Buddhism', max_length=50, verbose_name='ສາດສະໜາ (宗教)'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ຊື່ ແລະ ນາມສະກຸນລາວ(真实姓名)'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='name_Chinese',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='ຊື່ ແລະ ນາມສະກຸນພາສາຈີນ ຫຼື ອັງກິດ(真实姓名)'),
        ),
    ]
