# Generated by Django 6.0.6 on 2026-07-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_formresponse_ethnicity_formresponse_religion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='ethnicity_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ຊົນເຜົ່າອື່ນໆ (请ກອກຊົນເຜົ່າຂອງທ່ານ)'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='religion_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ສາດສະໜາອື່ນໆ (请ກອກສາດສະໜາຂອງທ່ານ)'),
        ),
    ]
