# Generated by Django 6.0.6 on 2026-07-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_formresponse_ethnicity_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='name_Chinese',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='ຊື່ແທ້ພາສາຈີນ ຫຼື ອັງກິດ(真实姓名)'),
        ),
    ]
