# Generated by Django 6.0.6 on 2026-07-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_formresponse_name_chinese'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='student_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
