# Generated by Django 6.0.6 on 2026-07-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_formresponse_student_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='name_Chinese',
            field=models.CharField(blank=True, max_length=255, verbose_name='ຊື່ແທ້ພາສາຈີນ ຫຼື ອັງກິດ(真实姓名)'),
        ),
    ]
