"""
Django settings for mywebvita project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/
221
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from import_export.formats.base_formats import CSV, XLSX, HTML, JSON, ODS
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-fk@6pwez0#@6jgt2&lg8_0nx+-c8qa4ri(ryu%x8449&k%_cp%"
# SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG =config("DEBUG", cast=bool)

DEBUG =True
# AGE =config("AGE", cast=int)

ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS =config("ALLOWED_HOSTS").split(",")

# 🔥 ເພີ່ມໂດເມນຂອງ Railway ເຂົ້າໄປເພື່ອໃຫ້ຜ່ານລະບົບຄວາມປອດໄພ CSRF
CSRF_TRUSTED_ORIGINS = [
    'https://cv-production-6318.up.railway.app/',
]

# ALLOWED_HOSTS = ['192.168.100.34','192.168.100.184','localhost', '127.0.0.1','.ngrok-free.app']

# Application definition

INSTALLED_APPS = [
    'simpleui', # <---- HERE
    'django_extensions',  # <--- ປ່ຽນມາເປັນຕົວນີ້
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp.apps.MyappConfig',
    'import_export',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 🔥 ເພີ່ມແຖວນີ້
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mywebvita.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
    os.path.join(BASE_DIR, 'templates'),
    os.path.join(BASE_DIR, 'myapp', 'templates'), 
],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mywebvita.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'vita_database',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#     }
# }

# DATABASES = {
#      'default': {
#         'ENGINE': 'mysql.connector.django',
#         'NAME': 'VITA_DATABASEPC',
#         'USER':'root',
#         'PASSWORD':'adminsomphone',
#         'HOST':'127.0.0.1',
#         'PORT':'3306',
#         'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",},
#      }
#  }

# DATABASES= {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'vita_databasepc',
#         'USER':'postgres',
#         'PASSWORD':'adminsomphone',
#         'HOST':'localhost',
#         'PORT':'5432'
#      }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# DATABASES['default'] = dj_database_url.parse(config("DATABASE_URL"))

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


IMPORT_FORMATS = [CSV,XLSX, HTML, ODS]

# single export options
EXPORT_FORMATS = [XLSX,CSV,HTML,ODS]
STATIC_URL = '/static/'  
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'myapp', 'static')]
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_LOGO ='/mywebvita/myapp/static/images/logo1.png'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (for user-uploaded content like photos)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
